#ddev-generated
rabbitmq:
  vhost:
    - host1
    - host2
  queue:
    - name: ddev-queue
      vhost: /
      durable: true
    - name: ddev-additional
      vhost: /
      durable: true
  user:
      - name: ddev-admin
        password: password
        tags:
          - administrator
          - management
        permissions:
          - vhost: /
            conf: .*
            write: .*
            read: .*
      - name: ddev-read
        password: password
        tags:
          - policymaker
  plugins:
      - rabbitmq_management
